name = "JPE"
uuid = "91eb96a3-1e89-498f-bca9-95862dab51bb"
authors = ["Florian Oswald <florian.oswald@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Cleaner = "caabdcdb-0ab6-47cf-9f62-08858e44f38f"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CSV = "0.10.15"
Chain = "0.6.0"
Cleaner = "1.1.1"
Conda = "1.10.2"
DataFrames = "1.7.0"
DataFramesMeta = "0.15.4"
Dates = "1.11.0"
DuckDB = "1.2.2"
Infiltrator = "1.9.1"
PyCall = "1.96.4"
RCall = "0.14.8"
Revise = "3.7.6"
Term = "2.0.7"
Test = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
