name = "JPE"
uuid = "91eb96a3-1e89-498f-bca9-95862dab51bb"
version = "1.0.0-DEV"
authors = ["Florian Oswald <florian.oswald@gmail.com> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Cleaner = "caabdcdb-0ab6-47cf-9f62-08858e44f38f"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MD5 = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
CSV = "0.10.15"
Chain = "0.6.0"
Cleaner = "1.1.1"
Conda = "1.10.2"
Crayons = "4.1.1"
DataFrames = "1.7.0"
DataFramesMeta = "0.15.4"
Dates = "1.11.0"
DuckDB = "1.2.2"
HTTP = "1.10.19"
Infiltrator = "1.9.1"
JSON = "0.21.4, 1"
MD5 = "0.2.3"
PrettyTables = "2.3.1"
PyCall = "1.96.4"
RCall = "0.14.8"
REPL = "1.11.0"
Random = "1.11.0"
Revise = "3.7.6"
Statistics = "1.11.0"
Term = "2.0.7"
Test = "1.11.0"
Unicode = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
